package model

import (
	"context"

	"gorm.io/gorm"
)

const (
	AgentProxyRouteKindTeams = "teams"
	AgentProxyRouteKindLine  = "line"
)

// AgentProxyRoute stores public reverse-proxy routes generated by Hatchery.
//
// The table is tenant-scoped: Identifier is automatically set/filtered by the
// GORM identifier callbacks. For external webhook requests, the HTTP Host is
// resolved by IdentifierMiddleware before this model is queried.
type AgentProxyRoute struct {
	gorm.Model
	Identifier string `gorm:"size:191;not null;default:'';index;uniqueIndex:idx_proxy_route_instance_kind,priority:1" json:"-"`
	RouteID    string `gorm:"size:64;not null;uniqueIndex" json:"route_id"`
	InstanceID string `gorm:"size:64;not null;index;uniqueIndex:idx_proxy_route_instance_kind,priority:2" json:"instance_id"`
	Kind       string `gorm:"size:32;not null;index;uniqueIndex:idx_proxy_route_instance_kind,priority:3" json:"kind"`
	TargetIP   string `gorm:"size:64;not null;default:''" json:"target_ip"`
	TargetPort int    `gorm:"not null;default:0" json:"target_port"`
	TargetPath string `gorm:"size:255;not null;default:''" json:"target_path"`
	Enabled    bool   `gorm:"not null;default:true" json:"enabled"`
}

// DisableAgentProxyRoutesForInstance disables all proxy routes bound to a CVM instance.
// Call this before deleting/soft-deleting an Instance row so opaque public URLs stop resolving immediately.
func DisableAgentProxyRoutesForInstance(ctx context.Context, cvmInstanceID string) error {
	if cvmInstanceID == "" {
		return nil
	}
	return DB(ctx).Model(&AgentProxyRoute{}).
		Where("instance_id = ?", cvmInstanceID).
		Update("enabled", false).Error
}

// DisableAgentProxyRoutesForUser disables proxy routes for all instances owned by a user.
// Used before batch soft-deleting instances during identity deletion.
func DisableAgentProxyRoutesForUser(ctx context.Context, userID uint) error {
	if userID == 0 {
		return nil
	}
	var cvmIDs []string
	if err := DB(ctx).Model(&Instance{}).
		Where("user_id = ? AND instance_id <> ''", userID).
		Pluck("instance_id", &cvmIDs).Error; err != nil {
		return err
	}
	if len(cvmIDs) == 0 {
		return nil
	}
	return DB(ctx).Model(&AgentProxyRoute{}).
		Where("instance_id IN ?", cvmIDs).
		Update("enabled", false).Error
}
